## 开发环境
server:  
  port: 8080

## 据源配置
spring: 
  ## thymeleaf 配置 
  thymeleaf: 
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  cache: 
    type: redis
  #---- redis设置   ----#
  redis:  
    database: 0
    host: localhost
    port: 6379
    password: 
    # 连接超时时间 单位 ms（毫秒）
    timeout: 6000
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  #---- 线程池配置 ----#
  task: 
    pool:
      core-pool-size: 5
      keep-alive-seconds: 100
      max-pool-size: 20
      queue-capacity: 8
      
logging: 
  config: classpath:config/logback-spring.xml
  
queueName: queue.mail
topicName: topic.pub
  

    