## 生产环境
server:  
  port: 80

## 据源配置
spring: 
  ## thymeleaf 配置 
  thymeleaf: 
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  cache: 
    type: redis
  #---- redis设置   ----#
  redis:  
    database: 0
    host: localhost
    port: 6379
    password: 
    # 连接超时时间 单位 ms（毫秒）
    timeout: 6000
    # 连接池中的最大空闲连接，默认值也是8。
    pool: 
      max-idle: 10
      #连接池中的最小空闲连接，默认值也是0。
      min-idle: 0
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-active: 10
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: -1
  #---- 线程池配置 ----#
  task: 
    pool:
      core-pool-size: 5
      keep-alive-seconds: 100
      max-pool-size: 20
      queue-capacity: 8
      
logging: 
  config: classpath:config/logback-spring.xml
  
queueName: queue.mail
topicName: topic.pub
  

    