
server:
  port: 8081

spring:

  cache:
    type: redis
  #---- redis配置  ----#
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 6000
    pool:
      max-idle: 10
      min-idle: 0
      max-active: 10
      max-wait: -1

