
spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: dev
    include: data

  activemq:
    broker-url: tcp://47.104.241.41:61616
    #mq账户密码
    user: admin
    password: pass123

  cache:
    type: redis




